name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir -p dist/css
          mkdir -p dist/js
          mkdir -p dist/images
          cp -r src/css/* dist/css
          cp -r src/js/* dist/js
          cp -r src/images/* dist/images

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages